---

- hosts: vagrant
  user: vagrant
  sudo: yes
  gather_facts: no
  connection: ssh

  roles:
    - fireball

# Switch to fireball mode
- hosts: vagrant
  user: vagrant 
  # sudo: True
  connection: fireball
  # port: 5100

  roles:
    - base-config
    - nginx
    - php-fpm
    - mariadb
    - memcache
    - phpmyadmin
    - ssmtp
