---
- hosts: vagrant
  user: vagrant 
  sudo: True

  vars_files:
    - config.yml
    - tuning.yml

  tasks:
  - include: site-deployment/tasks-distro.yml

  handlers: 
    - include: nginx/handlers.yml
    - include: php-fpm/handlers.yml
