---      
- name: install memcache
  apt: name=$item state=installed
  with_items:
    - memcached
    - php5-memcache

- name: memcache config
  template: src=memcached.conf.j2 
            dest=/etc/memcached.conf
  notify: 
    - restart memcached
